// Auto-generated list of the user's Lovable projects with published URLs.
export type LovableProject = { name: string; url: string };

export const MY_LOVABLE_PROJECTS: LovableProject[] = [
  { name: "Smart Solutions Hub", url: "https://hn-gr.lovable.app" },
  { name: "CarWashManager", url: "https://hn-carwash.lovable.app" },
  { name: "HN Adhkar Hub", url: "https://adhkarly-soulful-remembrance.lovable.app" },
  { name: "HN Driver", url: "https://smooth-route-guide.lovable.app" },
  { name: "Agency Hub Pro", url: "https://hn-immobiler.lovable.app" },
  { name: "HN Builder Studio", url: "https://prompt-build-magic-14.lovable.app" },
  { name: "hn-cima", url: "https://hn-vi.lovable.app" },
  { name: "AI Scene Studio", url: "https://hn-aivideo.lovable.app" },
  { name: "Cloud Harmony", url: "https://embrace-cloud-sync.lovable.app" },
  { name: "Creative Digital Studio", url: "https://spark-design-world.lovable.app" },
  { name: "HN Chat Hub", url: "https://hnchat.lovable.app" },
  { name: "Souk-HN Express", url: "https://souk-hn.lovable.app" },
  { name: "HN Apps Hub", url: "https://hn-app-hub.lovable.app" },
  { name: "HN Game Hub", url: "https://holo-game-galaxy.lovable.app" },
  { name: "V-Facture", url: "https://vfacture-hub.lovable.app" },
  { name: "Global Knowledge Hub", url: "https://globalknowledge-nexus.lovable.app" },
  { name: "HN Academy Hub", url: "https://hn-future-learn.lovable.app" },
  { name: "Taltna Connect", url: "https://taltna-global-hub.lovable.app" },
  { name: "HN Finance Hub", url: "https://money-wise-atlas.lovable.app" },
  { name: "Studio HN", url: "https://studio-hn.lovable.app" },
  { name: "AI Resume Genius", url: "https://hire-me-genius.lovable.app" },
  { name: "Neon AI Academy", url: "https://hn-tech-ai.lovable.app" },
  { name: "Database Foundation", url: "https://db-guard.lovable.app" },
  { name: "AI Studio Vision", url: "https://hn-videoai.lovable.app" },
  { name: "Remix of CarWashManager", url: "https://wash-pal-app.lovable.app" },
  { name: "Domain Monitor", url: "https://forever-friend-bot.lovable.app" },
  { name: "Grand Tanger Print Studio", url: "https://tangier-print-hub.lovable.app" },
  { name: "Profitable Ventures Hub", url: "https://income-igniter-ide.lovable.app" },
  { name: "AI Client Connect", url: "https://clinic-flowai.lovable.app" },
];
